### ISSUE TITLE
Problem with passwords in xml conf file

### ISSUE THREAD

**Issue by tang01** [Cougar/lg#1]
Dear Cougar,

I install lg on a Debian box, with all requested perl packages. It works fine, but I have an issue with some password's special characters in XML file.
For exemple the "&" character crash the browsing. It seems it's not allowed.
The workaround I found is to modify the lg.cgi file, with a kind of search and replace from a specific character chain in $password variable to the real character "&".

Can you please have a look on using & character in passwords ?

Thanks
Tanguy

**Comment by Cougar** [comment]
Hi Tanguy,

"&" is not allowed like other special XML characters. There are five such characters that needs to be escaped:

<table>
<tr><td>&quot;</td><td>&amp;quot;</td></tr>
<tr><td>&apos;</td><td>&amp;apos;</td></tr>
<tr><td>&lt;</td><td>&amp;lt;</td></tr>
<tr><td>&gt;</td><td>&amp;gt;</td></tr>
<tr><td>&amp;</td><td>&amp;amp;</td></tr>
</table>


If you don't escape them then XML parser usually crash. You can probably see something also in Apache error_log file. Let me know if it did help you.

Cheers,

Cougar
